# Generated by Django 5.0.2 on 2025-06-06 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicom_files/')),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_id', models.CharField(blank=True, max_length=255)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_description', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(blank=True, max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
