# Generated by Django 5.0.2 on 2025-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0002_series_alter_dicomfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
