# Generated by Django 5.0.2 on 2025-06-11 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacs', '0003_dicomfile_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='series',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='series',
            name='modality',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_instance_uid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_set', to='pacs.study'),
        ),
        migrations.AlterField(
            model_name='series',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='study',
            name='patient_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_instance_uid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
